markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif

#gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-56659912-1
disqus_id: mogopay

repository: https://github.com/mogobiz
help_url: https://github.com/mogobiz/mogobiz-help

collections:
  docs:
    output: true
