# Dependencies
markdown:		kramdown
highlighter:	pygments

# Permalinks
permalink:		pretty

# Setup
title:			'Mogobiz Documentation'
url:			http://www.mogobiz.com/doc/user/
baseurl:		/doc/user
encoding:		utf-8

author:
  name:			'Ahmad Ibrahim'
